export const TLSearchApplicationConfig = () => {
  return {
    label: "TL_SEARCH_APPLICATIONS",
    type: "search",
    apiDetails: {
      serviceName: "/tl-services/v1/_search",
      requestParam: {
        sortBy: "commencementDate",
        sortOrder: "DESC",
        limit: 10,
        offset: 0,
      },
      minParametersForSearchForm: 1,
      masterName: "commonUiConfig",
      moduleName: "TLSearchApplicationConfig",
      tableFormJsonPath: "requestParam",
      filterFormJsonPath: "requestParam",
      searchFormJsonPath: "requestParam",
    },
    sections: {
      search: {
        uiConfig: {
          headerStyle: null,
          formClassName: "",
          primaryLabel: "ES_COMMON_SEARCH",
          secondaryLabel: "ES_COMMON_CLEAR_SEARCH",
          minReqFields: 1,
          // showFormInstruction: "ES_SEARCH_APPLICATION_ERROR",
          defaultValues: {
            applicationNumber: "",
            applicationType: "",
            fromDate: "",
            toDate: "",
            licenseNumbers: "",
            status: "",
            tradeName: "",
          },
          fields: [
            {
              label: "TL_HOME_SEARCH_RESULTS_APP_NO_LABEL",
              type: "text",
              isMandatory: false,
              disable: false,
              populators: {
                name: "applicationNumber",
                error: "ERR_INVALID_APPLICATION_NO",
              },
            },
            {
              label: "TL_LOCALIZATION_APPLICATION_TYPE",
              type: "apidropdown",
              isMandatory: false,
              disable: false,
              populators: {
                name: "applicationType",
                optionsKey: "i18nKey",
                allowMultiSelect: false,
                masterName: "commonUiConfig",
                moduleName: "TLSearchApplicationConfig",
                customfn: "getApplicationType",
              },
            },
            {
              label: "TL_APPLICATION_FROM_DATE",
              type: "date",
              isMandatory: false,
              disable: false,
              key: "fromDate",
              populators: {
                name: "fromDate",
                max: "currentDate",
              },
            },
            {
              label: "TL_APPLICATION_TO_DATE",
              type: "date",
              isMandatory: false,
              disable: false,
              key: "toDate",
              populators: {
                name: "toDate",
                error: "DATE_VALIDATION_MSG",
                max: "currentDate",
              },
              additionalValidation: {
                type: "date",
                keys: {
                  start: "fromDate",
                  end: "toDate",
                },
              },
            },
            {
              label: "TL_TRADE_LICENSE_LABEL",
              type: "text",
              isMandatory: false,
              disable: false,
              populators: {
                name: "licenseNumbers",
                error: "ESTIMATE_PATTERN_ERR_MSG",
                validation: {
                  maxlength: 10,
                },
              },
            },
            {
              label: "TL_HOME_SEARCH_RESULTS_APP_STATUS_LABEL",
              type: "apidropdown",
              isMandatory: false,
              disable: false,
              populators: {
                name: "status",
                optionsKey: "i18nKey",
                allowMultiSelect: false,
                masterName: "commonUiConfig",
                moduleName: "TLSearchApplicationConfig",
                customfn: "getApplicationStatus",
              },
            },
            {
              label: "TL_LOCALIZATION_TRADE_NAME",
              type: "text",
              isMandatory: false,
              disable: false,
              populators: {
                name: "tradeName",
                error: "ESTIMATE_PATTERN_ERR_MSG",
              },
            },
          ],
        },
        label: "",
        children: {},
        show: true,
      },
      searchResult: {
        applicationNo: "",
        applicantName: "",
        mobileNumber: "",
        propertyType: "",
        subPropertyType: "",
        locality: "",
        status: "",
        uiConfig: {
          columns: [
            {
              key: "applicationNo",
              label: "TL_COMMON_TABLE_COL_APP_NO",
              jsonPath: "applicationNumber",
              additionalCustomization: true,
            },
            {
              key: "applicationDate",
              label: "TL_COMMON_TABLE_COL_APP_DATE",
              jsonPath: "auditDetails.createdTime",
              additionalCustomization: true,
            },
            {
              key: "applicationType",
              label: "TL_APPLICATION_TYPE_LABEL",
              jsonPath: "workflowCode",
              additionalCustomization: true,
            },
            {
              key: "licenseNumber",
              label: "TL_LICENSE_NUMBERL_LABEL",
              jsonPath: "licenseNumber",
            },
            {
              key: "financialYear",
              label: "TL_LICENSE_YEAR_LABEL",
              jsonpath: "financialYear",
              additionalCustomization: true,
            },
            {
              key: "tradeName",
              label: "TL_COMMON_TABLE_COL_TRD_NAME",
              jsonPath: "tradeName",
            },
            {
              key: "owners",
              label: "TL_LOCALIZATION_TRADE_OWNER_NAME",
              jsonPath: "tradeLicenseDetail.owners",
              additionalCustomization: true,
            },
            {
              key: "currentOwner",
              label: "WF_INBOX_HEADER_CURRENT_OWNER",
              jsonPath: "CurrentOwners.CurrentOwners",
              additionalCustomization: true,
            },
            {
              key: "status",
              label: "TL_COMMON_TABLE_COL_STATUS",
              jsonPath: "status",
              additionalCustomization: true,
            },
          ],
          enableGlobalSearch: false,
          enableColumnSort: true,
          resultsJsonPath: "Licenses",
        },
        children: {},
        show: true,
      },
    },
    additionalSections: {},
  };
};
